// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function readSupabaseConfig() {
  const metaEnv = import.meta.env;
  const runtimeEnv = typeof process !== 'undefined' ? process.env : undefined;
  const url = metaEnv?.['VITE_SUPABASE_URL'] || runtimeEnv?.['SUPABASE_URL'];
  const key = metaEnv?.['VITE_SUPABASE_PUBLISHABLE_KEY'] || runtimeEnv?.['SUPABASE_PUBLISHABLE_KEY'];
  return { url, key };
}

export function isSupabaseConfigured(): boolean {
  const { url, key } = readSupabaseConfig();
  return typeof url === 'string' && url.length > 0 && typeof key === 'string' && key.length > 0;
}

export function getSupabaseConfigError(): string | null {
  const { url, key } = readSupabaseConfig();
  const missing = [
    ...(!url ? ['VITE_SUPABASE_URL'] : []),
    ...(!key ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
  ];
  return missing.length
    ? `Configuration Supabase manquante : ${missing.join(', ')}. Connecte Supabase dans Lovable Cloud puis republie le site.`
    : null;
}

function createSupabaseClient() {
  const { url, key } = readSupabaseConfig();

  if (!url || !key) {
    const message = getSupabaseConfigError() ?? 'Configuration Supabase invalide.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(url, key, {
    global: {
      fetch: createSupabaseFetch(key),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
